overrides:
  '@types/react': 19.2.15
  '@types/react-dom': 19.2.3

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
